name: Vuepress Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: false

      - name: Install and Build ðŸ”§
        run: |
          npm install yarn
          yarn
          yarn docs:build
          echo sigure.xyz > docs/.vuepress/dist/CNAME

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REPOSITORY_NAME: SigureMo/SigureMo.github.io
          BRANCH: master
          FOLDER: docs/.vuepress/dist

      - name: Sync to Gitee ðŸ”€
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:SigureMo/SigureMo.github.io.git"
          destination-repo: "git@gitee.com:siguremo/SigureMo.git"

      - name: Build Gitee Pages ðŸ‘·
        uses: yanglbme/gitee-pages-action@master
        with:
          gitee-username: SigureMo
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: SigureMo/SigureMo
